-- MySQL Script generated by MySQL Workbench
-- Sat May  6 07:52:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sobrenome` VARCHAR(45) NULL,
  `descricao` VARCHAR(300) NULL,
  `idade` INT NULL,
  `nascimento` DATE NULL,
  `foto` VARCHAR(2048) NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Modalidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Modalidade` (
  `ID` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `sigla` CHAR(2) NULL,
  `descricao` VARCHAR(300) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Postagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Postagem` (
  `ID` INT NOT NULL,
  `usuarioID` INT NOT NULL,
  `modalidadeID` INT NOT NULL,
  `data` DATE NULL,
  `foto` VARCHAR(2048) NULL,
  `conteudo` VARCHAR(300) NULL,
  PRIMARY KEY (`ID`),
  INDEX `Usuario_ID_idx` (`usuarioID` ASC) VISIBLE,
  INDEX `Modalidade_ID_idx` (`modalidadeID` ASC) VISIBLE,
  CONSTRAINT `Usuario_ID`
    FOREIGN KEY (`usuarioID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Modalidade_ID`
    FOREIGN KEY (`modalidadeID`)
    REFERENCES `mydb`.`Modalidade` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comentario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comentario` (
  `ID` INT NOT NULL,
  `postagemID` INT NOT NULL,
  `usuarioID` INT NOT NULL,
  `data` DATE NULL,
  `conteudo` VARCHAR(2048) NULL,
  `resposta` VARCHAR(300) NULL,
  PRIMARY KEY (`ID`),
  INDEX `Postagem_ID_idx` (`postagemID` ASC) VISIBLE,
  INDEX `Usuário_ID_idx` (`usuarioID` ASC) VISIBLE,
  CONSTRAINT `Postagem_ID`
    FOREIGN KEY (`postagemID`)
    REFERENCES `mydb`.`Postagem` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuário_ID`
    FOREIGN KEY (`usuarioID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Seguir`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Seguir` (
  `usuarioID` INT NOT NULL,
  `seguidor` INT NULL,
  `seguindo` INT NULL,
  PRIMARY KEY (`usuarioID`),
  CONSTRAINT `Usuário_ID`
    FOREIGN KEY (`usuarioID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reacao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reacao` (
  `usuarioID` INT NOT NULL,
  `postagemID` INT NOT NULL,
  `reacao` VARCHAR(45) NULL,
  PRIMARY KEY (`usuarioID`, `postagemID`),
  INDEX `Postagem_ID_idx` (`postagemID` ASC) VISIBLE,
  CONSTRAINT `Usuário_ID`
    FOREIGN KEY (`usuarioID`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Postagem_ID`
    FOREIGN KEY (`postagemID`)
    REFERENCES `mydb`.`Postagem` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
