-- MySQL Script generated by MySQL Workbench
-- Thu Mar 30 09:23:42 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Usuário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Usuário` ;

CREATE TABLE IF NOT EXISTS `Usuário` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Sobrenome` VARCHAR(45) NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Sexo` CHAR NULL,
  `Data de Nascimento` DATE NOT NULL,
  `Sobre mim` VARCHAR(200) NULL,
  `Premium` INT NULL,
  `Foto de Perfil` BINARY(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `Senha_UNIQUE` ON `Usuário` (`Senha` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Equipe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Equipe` ;

CREATE TABLE IF NOT EXISTS `Equipe` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Descrição` VARCHAR(200) NOT NULL,
  `Data de criação` DATE NULL,
  `Logo` BINARY(100) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Arte marcial`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Arte marcial` ;

CREATE TABLE IF NOT EXISTS `Arte marcial` (
  `Sigla` VARCHAR(10) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Origem` VARCHAR(45) NULL,
  `Descrição` VARCHAR(200) NULL,
  PRIMARY KEY (`Sigla`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Certificado`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Certificado` ;

CREATE TABLE IF NOT EXISTS `Certificado` (
  `ID` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Instituição` VARCHAR(45) NOT NULL,
  `Data` DATE NULL,
  `Sigla` VARCHAR(10) NULL,
  `Arte marcial` VARCHAR(45) NOT NULL,
  `Validade` DATE NOT NULL,
  `Usuário_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Usuário_ID`
    FOREIGN KEY (`Usuário_ID`)
    REFERENCES `Usuário` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Usuário_ID_idx` ON `Certificado` (`Usuário_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Calendário`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Calendário` ;

CREATE TABLE IF NOT EXISTS `Calendário` (
  `ID` INT NOT NULL,
  `Data` DATE NOT NULL,
  `Duração` INT NOT NULL,
  `Equipe_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Equipe_ID`
    FOREIGN KEY (`Equipe_ID`)
    REFERENCES `Equipe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Equipe_ID_idx` ON `Calendário` (`Equipe_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Atividade` ;

CREATE TABLE IF NOT EXISTS `Atividade` (
  `Sigla` VARCHAR(10) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Nivel` VARCHAR(10) NULL,
  `Descrição` VARCHAR(200) NOT NULL,
  `Repetições` INT NULL,
  `Duração` INT NULL,
  `Equipe_ID` INT NOT NULL,
  PRIMARY KEY (`Sigla`),
  CONSTRAINT `Equipe_ID`
    FOREIGN KEY (`Equipe_ID`)
    REFERENCES `Equipe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Equipe_ID_idx` ON `Atividade` (`Equipe_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pertençe`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pertençe` ;

CREATE TABLE IF NOT EXISTS `Pertençe` (
  `ID` INT NOT NULL,
  `Função` VARCHAR(45) NOT NULL,
  `Data de entrada` DATE NOT NULL,
  `Data de saida` DATE NULL,
  `Usuário_ID` INT NOT NULL,
  `Equipe_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Equipe_ID`
    FOREIGN KEY (`Equipe_ID`)
    REFERENCES `Equipe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Usuário_ID`
    FOREIGN KEY (`Usuário_ID`)
    REFERENCES `Usuário` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Equipe_ID_idx` ON `Pertençe` (`Equipe_ID` ASC) VISIBLE;

CREATE INDEX `Usuário_ID_idx` ON `Pertençe` (`Usuário_ID` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Participa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Participa` ;

CREATE TABLE IF NOT EXISTS `Participa` (
  `ID` INT NOT NULL,
  `Sigla` VARCHAR(10) NULL,
  `Início` INT NOT NULL,
  `Fim` INT NOT NULL,
  `Status` VARCHAR(45) NULL,
  `Usuário_ID` INT NOT NULL,
  `Atividade_Sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Usuário_ID`
    FOREIGN KEY (`Usuário_ID`)
    REFERENCES `Usuário` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Atividade_Sigla`
    FOREIGN KEY (`Atividade_Sigla`)
    REFERENCES `Atividade` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Usuário_ID_idx` ON `Participa` (`Usuário_ID` ASC) VISIBLE;

CREATE INDEX `Atividade_Sigla_idx` ON `Participa` (`Atividade_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Pratica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Pratica` ;

CREATE TABLE IF NOT EXISTS `Pratica` (
  `ID` INT NOT NULL,
  `Usuário_ID` INT NOT NULL,
  `Arte marcial_Sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Usuário_ID`
    FOREIGN KEY (`Usuário_ID`)
    REFERENCES `Usuário` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Arte marcial_Sigla`
    FOREIGN KEY (`Arte marcial_Sigla`)
    REFERENCES `Arte marcial` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Usuário_ID_idx` ON `Pratica` (`Usuário_ID` ASC) VISIBLE;

CREATE INDEX `Arte marcial_Sigla_idx` ON `Pratica` (`Arte marcial_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Tem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tem` ;

CREATE TABLE IF NOT EXISTS `Tem` (
  `ID` INT NOT NULL,
  `Equipe_ID` INT NOT NULL,
  `Arte marcial_Sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Equipe_ID`
    FOREIGN KEY (`Equipe_ID`)
    REFERENCES `Equipe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Arte marcial_Sigla`
    FOREIGN KEY (`Arte marcial_Sigla`)
    REFERENCES `Arte marcial` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Equipe_ID_idx` ON `Tem` (`Equipe_ID` ASC) VISIBLE;

CREATE INDEX `Arte marcial_Sigla_idx` ON `Tem` (`Arte marcial_Sigla` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `Possui`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Possui` ;

CREATE TABLE IF NOT EXISTS `Possui` (
  `ID` INT NOT NULL,
  `Equipe_ID` INT NOT NULL,
  `Atividade_Sigla` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `Equipe_ID`
    FOREIGN KEY (`Equipe_ID`)
    REFERENCES `Equipe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Atividade_Sigla`
    FOREIGN KEY (`Atividade_Sigla`)
    REFERENCES `Atividade` (`Sigla`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `Equipe_ID_idx` ON `Possui` (`Equipe_ID` ASC) VISIBLE;

CREATE INDEX `Atividade_Sigla_idx` ON `Possui` (`Atividade_Sigla` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
